package com.seniorsteps.model;
// Generated Nov 21, 2020 2:55:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Content generated by hbm2java
 */
@Entity
@Table(name="content"
    ,catalog="online_courses"
)
public class Content  implements java.io.Serializable {


     private Integer id;
     private Course course;
     private String description;
     private Date period;
     private String title;
     private String videoId;

    public Content() {
    }

    public Content(Course course, String description, Date period, String title, String videoId) {
       this.course = course;
       this.description = description;
       this.period = period;
       this.title = title;
       this.videoId = videoId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COURSE_ID")
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="PERIOD", length=8)
    public Date getPeriod() {
        return this.period;
    }
    
    public void setPeriod(Date period) {
        this.period = period;
    }

    
    @Column(name="TITLE")
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="VIDEO_ID")
    public String getVideoId() {
        return this.videoId;
    }
    
    public void setVideoId(String videoId) {
        this.videoId = videoId;
    }




}


