package com.seniorsteps.model;
// Generated Nov 21, 2020 2:55:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Enrollment generated by hbm2java
 */
@Entity
@Table(name="enrollment"
    ,catalog="online_courses"
)
public class Enrollment  implements java.io.Serializable {


     private Integer id;
     private Course course;
     private Student student;
     private Date enrolDate;

    public Enrollment() {
    }

    public Enrollment(Course course, Student student, Date enrolDate) {
       this.course = course;
       this.student = student;
       this.enrolDate = enrolDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COURSE_ID")
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STUDENT_ID")
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENROL_DATE", length=19)
    public Date getEnrolDate() {
        return this.enrolDate;
    }
    
    public void setEnrolDate(Date enrolDate) {
        this.enrolDate = enrolDate;
    }




}


