package com.seniorsteps.model;
// Generated Nov 21, 2020 2:55:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Lookup generated by hbm2java
 */
@Entity
@Table(name="lookup"
    ,catalog="online_courses"
)
public class Lookup  implements java.io.Serializable {


     private Integer id;
     private String code;
     private String name;
     private String type;
     private Set<Course> courses = new HashSet<Course>(0);
     private Set<User> usersForGenderId = new HashSet<User>(0);
     private Set<Instructor> instructors = new HashSet<Instructor>(0);
     private Set<User> usersForTypeId = new HashSet<User>(0);

    public Lookup() {
    }

    public Lookup(String code, String name, String type, Set<Course> courses, Set<User> usersForGenderId, Set<Instructor> instructors, Set<User> usersForTypeId) {
       this.code = code;
       this.name = name;
       this.type = type;
       this.courses = courses;
       this.usersForGenderId = usersForGenderId;
       this.instructors = instructors;
       this.usersForTypeId = usersForTypeId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="CODE")
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="NAME")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="TYPE")
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="lookup")
    public Set<Course> getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set<Course> courses) {
        this.courses = courses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="lookupByGenderId")
    public Set<User> getUsersForGenderId() {
        return this.usersForGenderId;
    }
    
    public void setUsersForGenderId(Set<User> usersForGenderId) {
        this.usersForGenderId = usersForGenderId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="lookup")
    public Set<Instructor> getInstructors() {
        return this.instructors;
    }
    
    public void setInstructors(Set<Instructor> instructors) {
        this.instructors = instructors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="lookupByTypeId")
    public Set<User> getUsersForTypeId() {
        return this.usersForTypeId;
    }
    
    public void setUsersForTypeId(Set<User> usersForTypeId) {
        this.usersForTypeId = usersForTypeId;
    }




}


